### ISSUE TITLE
I saw your project and its great 👍 just some suggestion for css

### ISSUE THREAD

**Issue by Abhay557** [manishprasad9156/IBP_Project#1]
* {
    margin: 0px 3px 1px;
    padding: 0;
    box-sizing: border-box;
}
----------------------
.product img {
    width: 20em;
    justify-self: center;
    margin-right: 6em;
    padding: 2em 40px;
}
-------------------------
Try these changes

**Comment by manishprasad9156** [comment]
ThankYou @Abhay557 for pointing out this issue
